Projects module implementation
DouglasNeuroInformatics/DataBank pull request #43
Opened 2023-09-28 19:10 UTC by RyanHaniff

First implementation of the projects module based on #39

2023-09-29 17:22 UTC, joshunrau requested changes

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/dto/create-project.dto.ts
`@MinLength` is for validating strings, not arrays. Please see [this](https://stackoverflow.com/questions/58343262/class-validator-validate-array-of-objects) to learn how to validate arrays of nested objects.

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/dto/create-project.dto.ts
Why are you validating that`listOfManagers` is a string?

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/dto/create-project.dto.ts
Add validation for `listOfUsers`

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/dto/create-project.dto.ts
Add that all strings cannot be empty

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/dto/create-project.dto.ts
Double check that expiry is being coerced to a `Date` object here

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/dto/project-column.dto.ts
If a property can be undefined, please use this instead:

```js
class Foo {
  bar?: string
}
```

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/projects.controller.ts
Looks okay for now

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/projects.module.ts
Just make sure not to forget to call the service for create when done

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/projects.service.ts
Add error message for when not found

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/schemas/project-column.schema.ts
Key of T could not be any string if it is constrained by union. However, it could be a non-string which is what extract is filtering out

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/schemas/project-column.schema.ts
Add validation for the `type` prop (I think it is enum)

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/schemas/project.schema.ts
Add some validation that a `Date` object is actually being stored in db. If this is not the case, then you could change the expiry to be the timestamp

2023-09-29 17:22 UTC, joshunrau commented on api/src/projects/schemas/project.schema.ts
Why does project have data and columns? Should it not have a reference to the datasets (or datasets to projects?, can't remember what we agreed on in the meeting).

2023-09-29 17:22 UTC, joshunrau commented on types/index.d.ts
Why is `expiry` a number here but a date in other places? It should be consistent everywhere to avoid confusion. I recommend just using the timestamp everywhere.

2024-01-11 14:50 UTC, RyanHaniff commented on api/src/projects/schemas/project.schema.ts
Is this an acceptable way to validate Date?
``` ts
@Prop({ 
  required: true,
  type: Date,
  validate: {
    validator: (value: Date) => value instanceof Date,
    message: 'Expiry must be a valid Date object'
  }
})
expiry: Date;
```

2024-01-11 14:53 UTC, RyanHaniff commented on api/src/projects/schemas/project-column.schema.ts
In `index.d.ts` I added this enum:
``` ts
export enum ProjectColumnTypeEnum {
  STRING = 'STRING',
  FLOAT = 'FLOAT',
  INTEGER = 'INTEGER'
}
```
and modified this for `ProjectColumnType`
``` ts
  @Prop({ required: true, type: String, enum: Object.values(ProjectColumnTypeEnum) })
  type: ProjectColumnType;
```

2024-01-11 14:54 UTC, joshunrau commented on api/src/projects/schemas/project.schema.ts
If it is already coerced to date, then yes. Since Date is a standard object there should be no pitfalls with this. However, be carefully with `instanceof` since it is based on the very flawed prototype inheritance system, so if you are using multiple versions of the same library problems can arise.

2024-01-11 15:11 UTC, RyanHaniff commented on api/src/projects/dto/project-column.dto.ts
If I use the [ `@IsOptional`](https://github.com/typestack/class-validator#:~:text=ignores%20skipMissingProperties%20option.-,%40IsOptional(),-Checks%20if%20given) decorator is it redundant to still use `?:`
Example:
``` ts
  @IsOptional()
  name?: string;
```

2024-01-11 15:17 UTC, RyanHaniff commented on api/src/projects/dto/create-project.dto.ts
> Add that all strings cannot be empty

Is there a reason to set strings that are marked as `@IsOptional` to also not be empty?

2024-01-11 16:29 UTC, joshunrau commented on api/src/projects/dto/create-project.dto.ts
Step 1: Check if the value is either a `string` or `undefined`
Step 2: If the value if a string, check that it has a length greater than 0

2024-01-11 16:31 UTC, joshunrau commented on api/src/projects/dto/project-column.dto.ts
No, because the `name?: string` is assigning the type of string or undefined, while the decorator is doing that validation. Therefore, if you omit the `?`, at runtime you will have a value that is either a string or undefined, that is typed as always being a string. This issue is the main reason I am no longer using class validator. You need to make sure the values are correct, and then annotate the types. There is no type safety.

2024-01-11 16:32 UTC, joshunrau commented on api/src/projects/schemas/project-column.schema.ts
Okay

2024-02-23 16:07 UTC, closed without merging